preferSymlinkedExecutables: true
shellEmulator: true

trustPolicy: no-downgrade

linkWorkspacePackages: true
injectWorkspacePackages: true

packages:
    - apps/**/*
    - packages/**/*
    - tools/**/*
