import type { Entry } from "@animelist/packages-schema";
import { JSONSchema } from "@animelist/packages-schema";
import { open } from "@tauri-apps/plugin-dialog";
import { exists, readTextFile } from "@tauri-apps/plugin-fs";
import { err, ok } from "neverthrow";
import { ulid } from "ulidx";
import { parse } from "yaml";

export type FlatEntry = Omit<Entry, "children" | "related"> & {
    id: string;
    _parentId?: string;
    _isGeneratedId?: boolean;
};

class FileNotExists extends Error {
    constructor() {
        super();
        this.name = "FileNotExists";
    }
}

class InvalidFileFormat extends Error {
    constructor() {
        super();
        this.name = "InvalidFileFormat";
    }
}

const ID_PREFIX = "@autogenerated_";

export const StoreManager = {
    async pick() {
        const path = await open({
            filters: [{ name: "YAML", extensions: ["yml", "yaml"] }],
            multiple: false,
        });
        return path;
    },
    async readContent(path: string) {
        if (!(await exists(path))) {
            return err(new FileNotExists());
        }

        try {
            const contents = await readTextFile(path, { encoding: "utf-8" });

            const parsed = JSONSchema.safeParse(parse(contents));
            if (!parsed.success) {
                return err(new InvalidFileFormat());
            }

            return ok(parsed.data);
        } catch {
            return err(new InvalidFileFormat());
        }
    },
    flatten(entries: Entry[], parentId?: string) {
        const flatten: FlatEntry[] = [];

        for (const entry of entries) {
            const hasId = Boolean(entry.id);
            const id = entry.id ?? `${ID_PREFIX}${ulid()}`;

            const { children, related, ...rest } = entry;
            const flated: FlatEntry = {
                ...rest,
                id,
            };

            if (parentId) {
                flated._parentId = parentId;
            }

            if (!hasId) {
                flated._isGeneratedId = true;
            }

            flatten.push(flated);

            if (children && children.length > 0) {
                flatten.push(...this.flatten(children, id));
            }

            if (related && related.length > 0) {
                flatten.push(...this.flatten(related, id));
            }
        }

        return flatten;
    },
    buildMaps(flattenEntries: FlatEntry[]) {
        const indexMap = new Map<string, number>();
        const entryMap = new Map<string, FlatEntry>();

        for (let index = 0; index < flattenEntries.length; index++) {
            const entry = flattenEntries[index];
            if (!entry) {
                continue;
            }

            indexMap.set(entry.id, index);
            entryMap.set(entry.id, entry);
        }

        return { indexMap, entryMap };
    },
};
